In [1]:
import numpy as np

Numpy provides convenient methods to create arrays initilized with specific values like zeros and ones.

In [2]:
a1_zeros = np.zeros((3,3))

a2_ones = np.ones((2,2))

a3_range = np.arange(0,10,2)

print(a1_zeros)
print(a2_ones)
print(a3_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


As seen above, It has several built-in functions to generate arrays with specific properties.

1. np.zeros(): Creates an array filled with zeros.
2. np.ones(): Creates an array filled with ones.
3. np.full(): Creates an array filled with a specified value.
4. np.arange(): Creates an array with values that are evenly spaced within a given range.
5. np.linspace(): Creates an array with values that are evenly spaced over a specified interval.


In [3]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


1. Numpy.zeros():
numpy.zeros() function creates a new array of specified shapes and types, filled with zeros. It is beneficial when we need a placeholder array to initialize variables or store intermediate results. We can create 1D array using numpy.zeros().

Syntax:
numpy.zeros(shape, dtype = None, order = 'C') 

- shape: integer or sequence of integers – Defines the shape of the new array. Can be a single integer or a tuple.
- dtype: optional, default is float – The data type of the returned array. If not specified, the default is float.
- order: {‘C’, ‘F’} – Specifies the memory layout order:
   C-order: C-contiguous order means the last index varies the fastest. It is optimal for row-wise operations.

   F-order: FORTRAN-contiguous order means the first index varies the fastest. It is optimal for column-wise operations.

numpy.zeros() returns a new array filled with zeros, based on the specified shape and type.

In [4]:
arr = np.zeros(5)
print(arr)

arr = np.zeros((3, 4))# Creating a 2D array with 3 rows and 4 columns
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Specifying Data Type (dtype):

dtype parameter in numpy.zeros() defines the type of data stored in the array.

In [5]:
# Create an array of tuples with zeros
d = np.zeros((2, 2), dtype=[('f', 'f4'), ('i', 'i4')])
print(d)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


C vs F Order
Choosing the right memory layout can significantly improve performance, depending on our specific operations. If your operations are row-wise, use C-order. If they are column-wise, use F-order.

In [6]:
# Create a 2x3 array in C-order
e = np.zeros((2, 3), order='C')
print("C-order array:", e)

# Create a 2x3 array in F-order
f = np.zeros((2, 3), order='F')
print("F-order array:", f)

C-order array: [[0. 0. 0.]
 [0. 0. 0.]]
F-order array: [[0. 0. 0.]
 [0. 0. 0.]]


2. Numpy.ones():
The numpy.ones() function returns a new array of given shape and type, with ones.

Syntax:
numpy.ones(shape, dtype = None, order = 'C')

Parameters : 
shape : integer or sequence of integers
order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
dtype : [optional, float(byDefault)] Data type of returned array.  

Returns : 
ndarray of ones having given shape, order and datatype.


In [8]:
b = np.ones(2, dtype = int)
print("Matrix b :\n",  b)

a = np.ones([2, 2], dtype = int)
print("Matrix a :\n" , a)

c = np.ones([3, 3])
print("Matrix c :\n", c)

Matrix b :
 [1 1]
Matrix a :
 [[1 1]
 [1 1]]
Matrix c :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. numpy.full():

Syntax:
numpy.full(shape, fill_value, dtype = None, order = 'C')

Parameters :
shape      : Number of rows
order      : C_contiguous or F_contiguous
dtype      : [optional, float(by Default)] Data type of returned array.  
fill_value : [bool, optional] Value to fill in the array.

Returns :
ndarray

In [9]:
a = np.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n", a)

c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix a : 
 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


4. numpy.arrange():
It creates an array of evenly spaced values within a given interval. It is similar to Python's built-in range() function but returns a NumPy array instead of a list.

Syntax:
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

Parameters of numpy():
start (optional): The starting value of the sequence. Default is 0.
stop (required): The endpoint of the sequence, exclusive.
step (optional): The spacing between consecutive values. Default is 1.
dtype (optional): The desired data type of the output array.

Return Type:
Array of evenly spaced values.

In [12]:
# Creating a sequence of numbers from 0 to 9
sequence = np.arange(10)
print("Basic Sequence:", sequence)

# Creating a sequence of floating-point numbers from 0 to 1 
# with a step size of 0.2 using np.arange()
sequence = np.arange(0, 1, 0.2)
print("Floating-Point Sequence:", sequence)

#Combining with Conditional Filtering
# Creating a sequence of numbers from 0 to 20 
sequence = np.arange(0, 20, 3)

# Filtering the sequence to include only values greater than 10
filtered = sequence[sequence > 10]
print("Filtered Sequence:", filtered)

Basic Sequence: [0 1 2 3 4 5 6 7 8 9]
Floating-Point Sequence: [0.  0.2 0.4 0.6 0.8]
Filtered Sequence: [12 15 18]


5. numpy.linspace():
linspace() function in NumPy returns an array of evenly spaced numbers over a specified range.linspace() allows us to specify the total number of points we want in the array, and NumPy will calculate the spacing between the numbers automatically.

Syntax:
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Parameters:
start: [optional] start of interval range. By default start = 0
stop: end of interval range
num: [int, optional] No. of samples to generate
retstep: If True, Stop is the last sample By default restep = False
endpoint: If True, stop is included as the last value. If False, stop is excluded. By default endpoint=True.
dtype: type of output array
axis: If start and stop are arrays, axis specifies on what axis will the values be added. If axis = 0, value is added to front, if axis = -1 value is added at the end.

Return Type:
ndarray
step : [float, optional], if restep = True

In [15]:
#Including or Excluding the Stop Value
#By default, linspace() includes the stop value. However, you can exclude it by setting the endpoint parameter to False.

# Generate 10 numbers between 0 and 1
array_without_endpoint = np.linspace(0, 1, num=10, endpoint=False)

print(array_without_endpoint)

#Getting the Step Size
#retstep parameter allows you to return the step size between each number along with the array.

# Generate 5 numbers between 0 and 10 and return the step size
array, step = np.linspace(0, 10, num=5, retstep=True)

print("Step Size:", step)

#Multi-Dimensional Arrays
#We can also generate multi-dimensional arrays using linspace(). We can create a 2D array of numbers between 0 and 1:

# Create a 2D array of 5x5 numbers between 0 and 1
array_2d = np.linspace(0, 1, num=25).reshape(5, 5)

print(array_2d)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
Step Size: 2.5
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]
