In [1]:
import numpy as np

NumPy allows indexing and slicing operations on ndarrays which offers more flexibility to standard Python Lists.

1. Basic Indexing
We can access individual elements in an array using square brackets just like python lists.

In [2]:
arr = np.array([10,20,30,40,50])
print(arr[3])

40


2. Slicing
It allows us to extract sub-arrays using a range of indices.
Syntax:
[start:stop] where start is inclusive and stop is exclusive.

In [4]:
arr = np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


3. Multi-Dimentional Indexing
We can index and slice each dimension seperately in multi-dimenational arrays.This allows us to access specific rows,columns or deeper dimenstions of the array.

In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[1,2]) #outer array indexing, then inner array
print(arr_2d[0:2, 1:3]) # outer array slicing , then inner array

6
[[2 3]
 [5 6]]


Array Operations:
Numpy allows us to perform operations on entire arrays which enables efficient computation without the need for explicit loops.

1. Element-Wise Operations
These are straightforward and allows us to perform arithmetic operations on each element of the array directly.

In [7]:
arr = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(arr + arr_2)
print(arr - arr_2)
print(arr * arr_2)
print(arr / arr_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


2. Matrix Operations ( Dot product )
It allows us to multiply two arrays or matrices and get a single value or another matrix.

In [8]:
matrix1 = np.array([[1,2],
                    [3,4]])
matrix2 = np.array([[5,6],
                    [7,8]])
print(np.dot(matrix1,matrix2))

[[19 22]
 [43 50]]


3. Broadcasting 
This feature enables us to perform operations on arrays of different shapes. Numpy automatically adjusts the smaller array to match the shape of the larger for the operation.

In [9]:
arr = np.array([[1,2],
                [3,4]])
print(arr + 10)

[[11 12]
 [13 14]]


4. Reshaping and Flattening
Numpy provides functions to reshape or flatten arrays which is useful when working with machine learning or deep learning algorithms.

Reshaping:
Change the shape of an array while keeping the data same.

In [10]:
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


Flattening:
Convert multi-dimentional arrays into one - dimentional arrays.

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]
