In [1]:
import numpy as np

NumPy provides functions to create arrays filled with random numbers.

1. np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
2. np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
3. np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [2]:
random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))  

print(random_array)
print(normal_array)
print(randint_array)

[[0.96072405 0.80909503 0.91673939]
 [0.48814114 0.02741537 0.90802728]]
[[-2.73454719  0.4251867 ]
 [-0.99315393  0.74851863]]
[[3 2 5]
 [4 6 2]]


1. numpy.random.rand():

The numpy.random.rand() function creates an array of specified shapes fills it with random values uniformly distributed between 0 and 1.
It is commonly used for creating random arrays in various applications such as simulations and machine learning. The function's output is determined by the shape parameters provided.

Syntax : numpy.random.rand(d0, d1, ..., dn)

Parameters:
d0, d1, ..., dn : [int, optional]Dimension of the returned array we require, If no argument is given a single Python float is returned.
Return:

Array of defined shape, filled with random values.

In [3]:
#Randomly Constructing 1D Array
# 1D Array
array = np.random.rand(5)
print("1D Array filled with random values :", array);

#Randomly Constructing 2D Array 
# 2D Array   
array = np.random.rand(3, 4)
print("\n\n2D Array filled with random values : ", array);

#Randomly Constructing 3D Array 
# 3D Array     
array = np.random.rand(2, 2 ,2)
print("\n\n3D Array filled with random values : \n", array);

1D Array filled with random values : [0.07216959 0.80987969 0.37135413 0.57878499 0.04778371]


2D Array filled with random values :  [[0.42658702 0.6844734  0.82991172 0.75898093]
 [0.91288541 0.54459458 0.84174024 0.61399623]
 [0.74251287 0.04316395 0.21482454 0.83781725]]


3D Array filled with random values : 
 [[[0.84963161 0.36137584]
  [0.84422148 0.09714705]]

 [[0.91794652 0.9945612 ]
  [0.04371241 0.36914036]]]


2. numpy.random.randn():

The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution. 

If positive arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

Syntax:
numpy.random.randn(d0, d1, ..., dn)

Parameters : 
d0, d1, ..., dn : [int, optional]Dimension of the returned array we require, 
     If no argument is given a single Python float is returned.

Return : 
Array of defined shape, filled with random floating-point samples from 
the standard normal distribution.

In [4]:
#randomly constructing 1D array 

# 1D Array
array = np.random.randn(5)
print("1D Array filled with random values : \n", array);

#randomly constructing 2D array 
# 2D Array   
array = np.random.randn(3, 4)
print("2D Array filled with random values : \n", array);

#randomly constructing 3D array 
# 3D Array     
array = np.random.randn(2, 2 ,2)
print("3D Array filled with random values : \n", array);

#Manipulations with randomly created array 

# 3D Array     
array = np.random.randn(2, 2 ,2)
print("3D Array filled with random values : \n", array);
     
# Multiplying values with 3
print("\nArray * 3 : \n", array *3)

# Or we cab directly do so by 
array = np.random.randn(2, 2 ,2) * 3 + 2
print("\nArray * 3 + 2 : \n", array);

1D Array filled with random values : 
 [-0.43074356  1.74264704 -1.65746401 -0.61690796  1.02286713]
2D Array filled with random values : 
 [[ 0.51021644 -0.46987305  1.24270257 -1.96799457]
 [-0.03184291  0.95222588 -0.59563724  0.50739643]
 [-1.00139619  1.12113642 -0.09465235 -1.88854385]]
3D Array filled with random values : 
 [[[-0.96722084  0.96127986]
  [-1.58355837 -1.15561177]]

 [[-0.15352267  1.55695487]
  [ 1.33738424  0.05489337]]]
3D Array filled with random values : 
 [[[ 0.52712437  0.67644865]
  [-0.36379707 -0.51336127]]

 [[-0.64797862  0.38878123]
  [ 0.67227428  0.01038649]]]

Array * 3 : 
 [[[ 1.5813731   2.02934595]
  [-1.09139122 -1.54008381]]

 [[-1.94393586  1.16634368]
  [ 2.01682284  0.03115946]]]

Array * 3 + 2 : 
 [[[-1.29120599  0.11189044]
  [ 4.75172558  4.79424789]]

 [[-1.40890094  4.69304174]
  [ 1.50228686  5.05234491]]]


3. numpy.random.randint():
It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).

Syntax:
numpy.random.randint(low, high=None, size=None, dtype='l')

Parameters : 
low : [int] Lowest (signed) integer to be drawn from the distribution.But, it works as a highest integer in the sample if high=None. 
high : [int, optional] Largest (signed) integer to be drawn from the distribution.
size   :  [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
dtype      :  [optional] Desired output data-type.

Return  :  Array of random integers in the interval  [low, high)  or a single such random int if size not provided.

In [6]:
out_arr = np.random.randint(low = 0, high = 3, size = 5)
print ("Output 1D Array filled with random integers : ", out_arr)

out_arr = np.random.randint(low = 4, size =(2, 3))
print ("Output 2D Array filled with random integers : ", out_arr)

out_arr = np.random.randint(2, 10, (2, 3, 4))
print ("Output 3D Array filled with random integers : ", out_arr)

Output 1D Array filled with random integers :  [1 1 1 1 0]
Output 2D Array filled with random integers :  [[2 2 1]
 [1 0 3]]
Output 3D Array filled with random integers :  [[[3 7 5 5]
  [3 2 5 7]
  [2 7 2 7]]

 [[6 8 6 9]
  [5 8 2 7]
  [9 8 6 5]]]
