In [1]:
import numpy as np

NumPy provides functions to create specific types of matrices.

1. np.eye(): Creates an identity matrix of specified size.
2. np.diag(): Constructs a diagonal array.
3. np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
4. np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [2]:
identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


1. numpy.eye():

This function is often used to generate identity matrices with ones along the diagonal and zeros in all other positions.

Syntax:
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Parameters : 
R : Number of rows
C : [optional] Number of columns,By default M = N
k : [int, optional, 0 by default]
Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
dtype : [optional, float(by Default)] Data type of returned array.

In [4]:
# Creating a 3x5 rectangular matrix
rectangular_matrix = np.eye(3, 5)
print(rectangular_matrix)

#Specify a Diagonal Offset
#Specifying a diagonal offset refers to shifting the location of the diagonal filled with 1s within the matrix.

# Creating a 4x4 matrix with diagonal offset
matrix = np.eye(4, k=1)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


2. numpy.diag():

numpy.diag(a, k=0) : Extracts and construct a diagonal array 
Parameters : 

a : array_like 
k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

Returns : 
ndarray

In [5]:
# matrix creation by array input
a = np.matrix([[1, 21, 30], 
                 [63 ,434, 3], 
                 [54, 54, 56]])

print("Main Diagonal elements : \n", np.diag(a), "\n")

print("Diagonal above main diagonal : \n", np.diag(a, 1), "\n")

print("Diagonal below main diagonal : \n", np.diag(a, -1))

Main Diagonal elements : 
 [  1 434  56] 

Diagonal above main diagonal : 
 [21  3] 

Diagonal below main diagonal : 
 [63 54]


3. np.zeros_like():

This numpy method returns an array of given shape and type as given array, with zeros. 

Syntax:
numpy.zeros_like(array, dtype = None, order = 'K', subok = True)

Parameters : 
array : array_like input
subok  : [optional, boolean]If true, then newly created array will be sub-class of array; 
                 otherwise, a base-class array
order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
dtype  : [optional, float(byDefault)] Data type of returned array.  

Returns : 
ndarray of zeros having given shape, order and datatype.

In [6]:
array = np.arange(10).reshape(5, 2)
print("Original array : \n", array)


b = np.zeros_like(array, float)
print("\nMatrix b : \n", b)

array = np.arange(8)
c = np.zeros_like(array)
print("\nMatrix c : \n", c)

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix b : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Matrix c : 
 [0 0 0 0 0 0 0 0]


In [7]:
array = np.arange(10).reshape(5, 2)
print("Original array : \n", array)

array = np.arange(4).reshape(2, 2)
c = np.zeros_like(array, dtype = 'float')
print("\nMatrix  : \n", c)

array = np.arange(8)
c = np.zeros_like(array, dtype = 'float', order ='C')
print("\nMatrix  : \n", c)

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix  : 
 [[0. 0.]
 [0. 0.]]

Matrix  : 
 [0. 0. 0. 0. 0. 0. 0. 0.]


4. numpy.ones_like():

The numpy.one_like() function returns an array of given shape and type as a given array, with ones.

Syntax:
numpy.ones_like(array, dtype = None, order = 'K', subok = True)

Parameters :
array : array_like input
subok  : [optional, boolean]If true, then newly created array will be sub-class of array; 
                 otherwise, a base-class array
order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-wise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 
dtype  : [optional, float(byDefault)] Data type of returned array.  

Return:
ndarray of ones having given shape, order and datatype.

In [8]:
array = np.arange(10).reshape(5, 2)
print("Original array : \n", array)


b = np.ones_like(array, float)
print("\nMatrix b : \n", b)

array = np.arange(8)
c = np.ones_like(array)
print("\nMatrix c : \n", c)


Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix b : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Matrix c : 
 [1 1 1 1 1 1 1 1]
