In [1]:
import numpy as np

NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations. It offers functions for linear algebra and random number generation making it important for data science and machine learning.

Types of Array:

1. One dimentional Array (linear array)

In [3]:
list_1 = [1,2,3,4,5]

arr = np.array(list_1)

print("List in python:",list_1)
print(type(list_1))

print("Numpy Array in python:",arr)
print(type(arr))

List in python: [1, 2, 3, 4, 5]
<class 'list'>
Numpy Array in python: [1 2 3 4 5]
<class 'numpy.ndarray'>


2. Multi-Dimentional Array:

A Multi-Dimensional Array is an array that can store data in more than one dimension such as rows and columns. In simple terms it is a array of arrays. like table having rows and columns which can be accessed bu two indices,row and column.

In [4]:
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]
list_3 = [9,10,11,12]

arr = np.array([list_1,
                list_2,
                list_3])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Parameters of a Numpy Array:

1. Axis: Axis of an array describes the order of the indexing into the array.

Axis 0 = one dimensional
Axis 1 = Two dimensional
Axis 2 = Three dimensional 

2. Shape : Number of elements along with each axis and is returned as a tuple.

In [5]:
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


3. Rank: Rank of an array is simply the number of aces or dimentions it has.

1D has rank 1
2D has rank 2

4. Data type objects (dtype):
Data type objects (dtype) is an example of numpy.dtype class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.


In [6]:
sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64
